---
- name: Install_httpd on webservers
  hosts: webservers
  become: true
  tasks: 
    - name: Install HTTPD on webservers
      dnf:
        name: httpd
        state: present

    - name: start and enable HTTPD
      service:
        name: httpd
        state: started
        enabled: true
